### ISSUE TITLE
Publicly expose lower level functions (SqlReader, TDFReader, DIA table readers) to allow for flexible parsing options

### ISSUE THREAD

**Issue by arnscott** [MannLabs/timsrust#16]
Hello! Thanks for putting in the work on this crate! Very exciting to have some native support for timsTOF files in rust.

I was wondering if you had any plans on exposing some of the lower level functions in the crate for public use so they can be used through cargo. Structs such as the TDFReader, SqlReader, and the DIA table readers, would make it much easier to try and implement parsing for tools to analyze DIA data. I saw there was an open pull request regarding DIA data, but there doesn't seem to have been much movement on it recently.

Hope to hear back from you!

**Comment by sander-willems-bruker** [comment]
Hi @arnscott , thanks for the interest in TimsRust.

Indeed there has bene little activity due to more pressing priorities. By now I should be able to work on Timsrust more actively.

We purposefully tried to keep the API as small as possible to also keep it as simple as possible:
* Our first priority was to expose a method to just read MS2 spectra for DDA data, which really does not need any more endpoints than a file reader with associated spectrum reader.
* For MS1 data, exposing frames and all the converters became essential.
* We are now looking into proper DIA support (also addressed in the open PR you mentioned). We still need to decide on what will be exposed and what not, but please note that our aim remains to keep te open API as simple as possible.

All that said, feel free to recycle and copy-paste what you think is useful, or alternatively keep a local fork which exposes what you need as a current work around.
